import type { Metadata } from "next";
import "./globals.css";
import BottomNavbar from "@/components/layout/bottom-navbar";
import ProfileHeader from "./_components/profile-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ProfileHeader />

        <main className="mt-20">{children}</main>

        <BottomNavbar />
      </body>
    </html>
  );
}
